// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zombie_survival_3Dgame_Server.Data;

#nullable disable

namespace zombie_survival_3Dgame_Server.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Auth.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Auth.Models.AuthVerificationCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("AuthVerificationCodes");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Firearm.Models.FirearmDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("FireRate")
                        .HasColumnType("double");

                    b.Property<double>("GachaProbability")
                        .HasColumnType("double");

                    b.Property<double>("HeadshotDamageMultiplier")
                        .HasColumnType("double");

                    b.Property<int>("MagazineSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("RangeMeters")
                        .HasColumnType("double");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<double>("ReloadTimeSeconds")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FirearmDefinitions");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Inventory.Models.PlayerSaveData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerSaveData");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Inventory.Models.PlayerWeaponState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<double>("FireRate")
                        .HasColumnType("double");

                    b.Property<int>("FirearmDefinitionId")
                        .HasColumnType("int");

                    b.Property<double>("HeadshotDamageMultiplier")
                        .HasColumnType("double");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MagazineSize")
                        .HasColumnType("int");

                    b.Property<int>("PlayerSaveDataId")
                        .HasColumnType("int");

                    b.Property<double>("RangeMeters")
                        .HasColumnType("double");

                    b.Property<double>("ReloadTimeSeconds")
                        .HasColumnType("double");

                    b.Property<int>("WeaponLevel")
                        .HasColumnType("int");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FirearmDefinitionId");

                    b.HasIndex("PlayerSaveDataId", "FirearmDefinitionId")
                        .IsUnique();

                    b.ToTable("PlayerWeaponStates");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Player.Models.PlayerStatUpgradeState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerSaveDataId")
                        .HasColumnType("int");

                    b.Property<string>("StatName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerSaveDataId", "StatName")
                        .IsUnique();

                    b.ToTable("PlayerStatUpgradeStates");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Inventory.Models.PlayerWeaponState", b =>
                {
                    b.HasOne("zombie_survival_3Dgame_Server.Firearm.Models.FirearmDefinition", "FirearmDefinition")
                        .WithMany()
                        .HasForeignKey("FirearmDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("zombie_survival_3Dgame_Server.Inventory.Models.PlayerSaveData", "PlayerSaveData")
                        .WithMany("WeaponStates")
                        .HasForeignKey("PlayerSaveDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FirearmDefinition");

                    b.Navigation("PlayerSaveData");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Player.Models.PlayerStatUpgradeState", b =>
                {
                    b.HasOne("zombie_survival_3Dgame_Server.Inventory.Models.PlayerSaveData", "PlayerSaveData")
                        .WithMany("StatUpgradeStates")
                        .HasForeignKey("PlayerSaveDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerSaveData");
                });

            modelBuilder.Entity("zombie_survival_3Dgame_Server.Inventory.Models.PlayerSaveData", b =>
                {
                    b.Navigation("StatUpgradeStates");

                    b.Navigation("WeaponStates");
                });
#pragma warning restore 612, 618
        }
    }
}
