name: CI

on:
  push:
    branches:
      - main
      - release
      - develop

  pull_request:
    branches:
      - main
      - release
      - develop

  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  PROJECT_PATH: /home/runner/work/zombie-survival-3Dgame-Server/zombie-survival-3Dgame-Server

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Inspect files
        run: |
          pwd
          find . -maxdepth 4 -name "*.csproj" -o -name "*.sln"
          
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --no-build
